@props(['shop' => null])

@php
    $feature = request()->route('feature');
    $guideKey = match (true) {
        request()->routeIs('seller.shops.storefront') => 'storefront',
        request()->routeIs('seller.shops.pos') => 'terminal',
        request()->routeIs('seller.shops.feature') => $feature,
        request()->routeIs('seller.shops.products.import.*', 'seller.shops.products.bulk.*') => 'import',
        request()->routeIs('seller.shops.products.*') => 'products',
        request()->routeIs('seller.shops.inventory.lots') => 'lots',
        request()->routeIs('seller.shops.inventory.*') => 'inventory',
        request()->routeIs('seller.shops.customers.*') => 'customers',
        request()->routeIs('seller.shops.cash.*') => 'cash',
        request()->routeIs('seller.shops.expenses.*') => 'expenses',
        request()->routeIs('seller.shops.business') => 'finance',
        request()->routeIs('seller.shops.metrics.*') => 'metrics',
        request()->routeIs('seller.shops.pricing.*') => 'pricing',
        request()->routeIs('seller.shops.categories.*') => 'attributes',
        request()->routeIs('seller.shops.sellers.*') => 'team',
        request()->routeIs('seller.shops.edit') => 'settings',
        default => null,
    };

    $guides = [
        'storefront' => ['eyebrow' => 'Catálogo', 'title' => 'Tu tienda se prepara aquí', 'description' => 'Completa lo esencial, compártela y revisa cómo la verá tu cliente.', 'steps' => [['title' => 'Completa tu información', 'text' => 'Logo, WhatsApp, descripción y dirección hacen confiable tu vitrina.'], ['title' => 'Revisa tu catálogo', 'text' => 'Publica productos con precio, existencia y una buena foto.'], ['title' => 'Compártela', 'text' => 'Copia el enlace, envíalo por WhatsApp o imprime tu código QR.']]],
        'terminal' => ['eyebrow' => 'Operación', 'title' => 'Vende en pocos pasos', 'description' => 'Busca productos, agrégalos al carrito y cobra sin perder el control del inventario.', 'steps' => [['title' => 'Busca o escanea', 'text' => 'Filtra por nombre, categoría o código y toca un producto para agregarlo.'], ['title' => 'Revisa el carrito', 'text' => 'Ajusta cantidades, cliente, precio detalle o mayorista y tipo de venta.'], ['title' => 'Cobra o cotiza', 'text' => 'El cobro descuenta inventario; la cotización reserva la intención sin tocarlo.']]],
        'sales' => ['eyebrow' => 'Operación', 'title' => 'Entiende cada venta', 'description' => 'Aquí puedes buscar ventas, filtrar el período y revisar cómo se originó cada cobro.', 'steps' => [['title' => 'Elige el período', 'text' => 'Compara hoy, los últimos días o un rango más amplio.'], ['title' => 'Busca y filtra', 'text' => 'Encuentra la venta por número, cliente, pago u origen.'], ['title' => 'Abre el detalle', 'text' => 'Confirma artículos, cobros, costo FIFO y ganancia real.']]],
        'quotes' => ['eyebrow' => 'Operación', 'title' => 'Una cotización es un precio por escrito', 'description' => 'Se prepara desde Terminal en modo Cotizar y no afecta el inventario hasta convertirla.', 'steps' => [['title' => 'Abre Terminal', 'text' => 'Cambia el modo de operación a Cotizar.'], ['title' => 'Arma el presupuesto', 'text' => 'Busca y agrega productos, cantidades, cliente y notas.'], ['title' => 'Envía o convierte', 'text' => 'Comparte el documento y conviértelo en venta cuando el cliente acepte.']]],
        'orders' => ['eyebrow' => 'Operación', 'title' => 'Los pedidos llegan aquí', 'description' => 'Comparte tu tienda para recibir órdenes y conviértelas en ventas cuando estén listas.', 'steps' => [['title' => 'Comparte tu catálogo', 'text' => 'El cliente abre tu enlace y arma su pedido desde el teléfono.'], ['title' => 'Confirma disponibilidad', 'text' => 'Revisa artículos, método de entrega y datos de contacto.'], ['title' => 'Pasa a venta', 'text' => 'Confirma el pedido para que quede registrado en tu operación.']]],
        'encargos' => ['eyebrow' => 'Operación', 'title' => 'Ordena tus encargos por entrega', 'description' => 'Registra lo que debes preparar, para quién y cuándo debe estar listo.', 'steps' => [['title' => 'Cobra o registra el encargo', 'text' => 'Guarda cliente, fecha y detalle del trabajo.'], ['title' => 'Trabaja por estado', 'text' => 'Separa abiertos, entregados y cancelados.'], ['title' => 'Entrega y cierra', 'text' => 'Completa el encargo y conserva su historial.']]],
        'shipments' => ['eyebrow' => 'Operación', 'title' => 'Controla cada envío', 'description' => 'Sabe quién lo lleva, dónde está y cuánto te costó entregar.', 'steps' => [['title' => 'Identifica la entrega', 'text' => 'Separa mostrador, recogida, delivery o courier.'], ['title' => 'Actualiza el estado', 'text' => 'Preparando, en camino, entregado o con problema.'], ['title' => 'Cierra el ciclo', 'text' => 'Conserva el costo y la trazabilidad del pedido.']]],
        'day_close' => ['eyebrow' => 'Operación', 'title' => 'Cierra el día con claridad', 'description' => 'Compara ventas, abonos, gastos, devoluciones y efectivo antes de cerrar.', 'steps' => [['title' => 'Revisa los movimientos', 'text' => 'El resumen muestra lo que entró y salió durante el día.'], ['title' => 'Cuenta la caja', 'text' => 'Registra el efectivo contado y compara contra lo esperado.'], ['title' => 'Cierra el día', 'text' => 'Después del cierre no se corrigen movimientos sin autorización.']]],
        'containers' => ['eyebrow' => 'Compras', 'title' => 'Cada compra conserva su costo', 'description' => 'Agrupa lo que compras a cada suplidor y recibe lotes con el costo exacto.', 'steps' => [['title' => 'Crea el contenedor', 'text' => 'Registra suplidor y documento antes de recibir mercancía.'], ['title' => 'Agrega productos', 'text' => 'Indica cantidad y costo unitario de esta compra.'], ['title' => 'Recibe', 'text' => 'El lote entra al inventario y participa en el costo FIFO.']]],
        'loads' => ['eyebrow' => 'Compras', 'title' => 'Reparte el costo de tus cargas', 'description' => 'Registra flete, libraje y aduana para conocer el costo real puesto.', 'steps' => [['title' => 'Crea la carga', 'text' => 'Identifica el envío y su fecha.'], ['title' => 'Asocia contenedores', 'text' => 'Agrupa las compras que viajan juntas.'], ['title' => 'Recibe con costo real', 'text' => 'La mercancía queda lista para vender con ganancia exacta.']]],
        'suppliers' => ['eyebrow' => 'Compras', 'title' => 'Tus suplidores, en un solo lugar', 'description' => 'Guarda a quién compras y consulta el historial que alimenta tu inventario.', 'steps' => [['title' => 'Registra el contacto', 'text' => 'Nombre, teléfono y correo para encontrarlo rápido.'], ['title' => 'Asocia compras', 'text' => 'Relaciona contenedores y facturas con cada suplidor.'], ['title' => 'Consulta saldos', 'text' => 'Usa el historial para decidir mejor tus próximas compras.']]],
        'purchase_invoices' => ['eyebrow' => 'Compras', 'title' => 'Las facturas respaldan tus costos', 'description' => 'Relaciona cada documento con los productos y lotes que realmente recibiste.', 'steps' => [['title' => 'Registra el documento', 'text' => 'Número, suplidor y fecha.'], ['title' => 'Detalla la recepción', 'text' => 'Producto, cantidad y costo unitario.'], ['title' => 'Verifica el lote', 'text' => 'El costo queda disponible para inventario y ganancias.']]],
        'products' => ['eyebrow' => 'Catálogo', 'title' => 'Tu catálogo empieza por productos claros', 'description' => 'Cada producto debe tener nombre, precio, existencia y la información que necesita tu cliente.', 'steps' => [['title' => 'Crea o importa', 'text' => 'Agrega uno a uno o usa la importación masiva.'], ['title' => 'Completa la ficha', 'text' => 'Categoría, marca, unidad, precio y costo.'], ['title' => 'Publícalo con confianza', 'text' => 'Revisa foto, disponibilidad y cómo se ve en tu tienda.']]],
        'inventory' => ['eyebrow' => 'Catálogo', 'title' => 'El inventario te dice qué puedes vender', 'description' => 'Controla existencias, alertas, lotes y costos sin duplicar movimientos.', 'steps' => [['title' => 'Busca y filtra', 'text' => 'Encuentra productos agotados, bajos o disponibles.'], ['title' => 'Recibe mercancía', 'text' => 'Cada recepción crea un lote con su costo.'], ['title' => 'Ajusta con motivo', 'text' => 'Registra pérdidas o conteos para mantener trazabilidad.']]],
        'lots' => ['eyebrow' => 'Catálogo', 'title' => 'FIFO conserva la ganancia real', 'description' => 'Cada lote recuerda cuánto costó y se vende primero el más antiguo.', 'steps' => [['title' => 'Recibe por lote', 'text' => 'No pises el costo anterior cuando compres más caro.'], ['title' => 'Vende primero lo antiguo', 'text' => 'El sistema consume los lotes en orden de entrada.'], ['title' => 'Mira la ganancia', 'text' => 'Cada venta queda ligada al costo que realmente salió.']]],
        'photos' => ['eyebrow' => 'Catálogo', 'title' => 'Una buena foto vende', 'description' => 'Completa imágenes en bloque y acepta solo las sugerencias que te den confianza.', 'steps' => [['title' => 'Revisa pendientes', 'text' => 'Separa por confirmar, sin foto y todas.'], ['title' => 'Busca sugerencias', 'text' => 'Encuentra imágenes para los productos que no tienen.'], ['title' => 'Acepta con control', 'text' => 'Nada cambia hasta que tú lo confirmas.']]],
        'services' => ['eyebrow' => 'Catálogo', 'title' => 'También puedes vender lo que haces', 'description' => 'Los servicios se cobran como productos, pero no descuentan inventario.', 'steps' => [['title' => 'Crea el servicio', 'text' => 'Nombre, precio y duración.'], ['title' => 'Cóbalo en Terminal', 'text' => 'Aparece junto a tu catálogo de productos.'], ['title' => 'Mide su resultado', 'text' => 'Consulta cobros y ganancia después de insumos.']]],
        'price_health' => ['eyebrow' => 'Catálogo', 'title' => 'Evita vender por debajo del costo', 'description' => 'Detecta precios sin margen o desactualizados antes de que afecten tu ganancia.', 'steps' => [['title' => 'Elige el margen objetivo', 'text' => 'Define cuándo un precio necesita atención.'], ['title' => 'Revisa sugerencias', 'text' => 'Compara costo, precio, margen y precio sugerido.'], ['title' => 'Corrige con intención', 'text' => 'Decide producto por producto sin cambios silenciosos.']]],
        'pricing' => ['eyebrow' => 'Catálogo', 'title' => 'Los precios se recalculan solos', 'description' => 'Define margen y redondeo una vez; las subidas pueden aplicarse automáticamente y las bajadas esperan tu revisión.', 'steps' => [['title' => 'Crea una regla', 'text' => 'Elige a qué productos aplica.'], ['title' => 'Define la fórmula', 'text' => 'Margen sobre el precio y redondeo.'], ['title' => 'Revisa las bajadas', 'text' => 'Un costo nuevo no rebaja tu catálogo sin tu visto bueno.']]],
        'decants' => ['eyebrow' => 'Catálogo', 'title' => 'Convierte botellas en oportunidades', 'description' => 'Controla tamaños, mililitros disponibles y costo compartido por lote.', 'steps' => [['title' => 'Define tus frascos', 'text' => 'Crea los tamaños que vendes.'], ['title' => 'Abre una botella', 'text' => 'Registra el volumen y su costo.'], ['title' => 'Prepara y vende', 'text' => 'El sistema descuenta mililitros con trazabilidad.']]],
        'attributes' => ['eyebrow' => 'Catálogo', 'title' => 'Los atributos mantienen ordenado tu catálogo', 'description' => 'Marcas, tallas, colores y categorías se corrigen desde un solo lugar.', 'steps' => [['title' => 'Elige el atributo', 'text' => 'Marca, género, tamaño o el que uses en tu negocio.'], ['title' => 'Corrige el nombre', 'text' => 'El cambio se refleja en todos los productos.'], ['title' => 'Filtra mejor', 'text' => 'Tus clientes encuentran lo que buscan más rápido.']]],
        'import' => ['eyebrow' => 'Catálogo', 'title' => 'Importa sin perder el control', 'description' => 'El importador adapta tus columnas, muestra una vista previa y guarda tu avance.', 'steps' => [['title' => 'Sube el archivo', 'text' => 'Usa Excel o CSV aunque tenga encabezados adicionales.'], ['title' => 'Corrige el mapeo', 'text' => 'Confirma dónde están nombre, precio, costo y existencia.'], ['title' => 'Importa con resumen', 'text' => 'Revisa creados, actualizados y filas con advertencias.']]],
        'customers' => ['eyebrow' => 'Cobros', 'title' => 'Conoce a quienes te compran', 'description' => 'Guarda el historial, el crédito y los cobros de cada cliente.', 'steps' => [['title' => 'Agrega el cliente', 'text' => 'Nombre y contacto para reconocerlo al vender.'], ['title' => 'Vende a crédito', 'text' => 'Selecciona el cliente desde Terminal y deja el saldo registrado.'], ['title' => 'Cobra abonos', 'text' => 'Cada pago reduce la cuenta por cobrar y actualiza tus finanzas.']]],
        'credit' => ['eyebrow' => 'Cobros', 'title' => 'Cobra lo que está en la calle', 'description' => 'Consulta quién debe, cuánto falta y registra abonos sin perder el historial.', 'steps' => [['title' => 'Filtra por estado', 'text' => 'Separa cuentas por cobrar y cuentas pagadas.'], ['title' => 'Abre la cuenta', 'text' => 'Revisa ventas, abonos y saldo pendiente.'], ['title' => 'Registra el cobro', 'text' => 'El abono actualiza caja y la ganancia realizada.']]],
        'cash' => ['eyebrow' => 'Finanzas', 'title' => 'La caja debe coincidir', 'description' => 'Abre una sesión, registra movimientos y concilia el efectivo al cierre.', 'steps' => [['title' => 'Abre la caja', 'text' => 'Indica el fondo inicial y la persona responsable.'], ['title' => 'Registra movimientos', 'text' => 'Entradas y salidas quedan separadas de las ventas.'], ['title' => 'Concilia', 'text' => 'Compara efectivo esperado contra el contado.']]],
        'finance' => ['eyebrow' => 'Finanzas', 'title' => 'Control financiero del negocio', 'description' => 'Ventas menos costos FIFO, gastos y pérdidas: así sabes qué dinero deja cada período.', 'steps' => [['title' => 'Elige el período', 'text' => 'Hoy, mes actual o una comparación anterior.'], ['title' => 'Lee la ganancia', 'text' => 'Costo de lo vendido y margen bruto con el lote real.'], ['title' => 'Decide mejor', 'text' => 'Usa productos más rentables para planificar compras.']]],
        'expenses' => ['eyebrow' => 'Finanzas', 'title' => 'Registra cada gasto', 'description' => 'Los gastos completan la visión de ganancia neta y ayudan a controlar costos.', 'steps' => [['title' => 'Crea la categoría', 'text' => 'Organiza alquiler, transporte, servicios u otros.'], ['title' => 'Registra el gasto', 'text' => 'Fecha, monto, método y nota.'], ['title' => 'Consulta el impacto', 'text' => 'Aparece en finanzas y reportes del período.']]],
        'inventory_adjustments' => ['eyebrow' => 'Finanzas', 'title' => 'Ajusta sin borrar la historia', 'description' => 'Documenta daño, desperdicio, robo o diferencias de conteo.', 'steps' => [['title' => 'Elige el producto', 'text' => 'Selecciona la referencia y cantidad.'], ['title' => 'Explica qué pasó', 'text' => 'El motivo es parte de la auditoría.'], ['title' => 'Registra la salida', 'text' => 'La pérdida se valora al costo y no toca la caja.']]],
        'partners' => ['eyebrow' => 'Finanzas', 'title' => 'Separa la operación de los socios', 'description' => 'Registra aportes, retiros y reparto de ganancias como control interno.', 'steps' => [['title' => 'Agrega el socio', 'text' => 'Define nombre y porcentaje.'], ['title' => 'Registra aportes', 'text' => 'Mantén el movimiento separado de las ventas.'], ['title' => 'Consulta el reparto', 'text' => 'La ganancia neta se calcula con ventas, costos y gastos.']]],
        'reports' => ['eyebrow' => 'Análisis', 'title' => 'Convierte datos en decisiones', 'description' => 'Consulta ventas, ganancia, stock y productos más vendidos en un período.', 'steps' => [['title' => 'Elige el período', 'text' => 'Compara el rendimiento de tu negocio.'], ['title' => 'Lee las métricas', 'text' => 'Ingresos, costo FIFO, ganancia e inventario.'], ['title' => 'Exporta', 'text' => 'Descarga CSV o Excel para compartir con tu contador.']]],
        'team' => ['eyebrow' => 'Equipo', 'title' => 'Cada persona ve lo que necesita', 'description' => 'Administra usuarios, vendedores y permisos sin exponer datos administrativos.', 'steps' => [['title' => 'Invita al equipo', 'text' => 'Agrega personas a la tienda con su correo.'], ['title' => 'Asigna permisos', 'text' => 'Define menús y acciones operativas.'], ['title' => 'Revisa accesos', 'text' => 'Suspende o reactiva sin borrar el historial.']]],
        'commissions' => ['eyebrow' => 'Equipo', 'title' => 'Las comisiones siguen la venta', 'description' => 'Consulta qué corresponde a cada vendedor en el período seleccionado.', 'steps' => [['title' => 'Elige la quincena', 'text' => 'Usa la fecha en que se hizo cada venta.'], ['title' => 'Revisa la base', 'text' => 'Ventas menos devoluciones y anulaciones.'], ['title' => 'Paga con datos', 'text' => 'El porcentaje queda ligado al vendedor de esa venta.']]],
        'authorizations' => ['eyebrow' => 'Equipo', 'title' => 'Las acciones sensibles esperan permiso', 'description' => 'Centraliza las solicitudes que requieren aprobación del propietario.', 'steps' => [['title' => 'El equipo solicita', 'text' => 'La petición conserva quién y qué quiere hacer.'], ['title' => 'Revisa el contexto', 'text' => 'Consulta la operación antes de responder.'], ['title' => 'Aprueba o rechaza', 'text' => 'El sistema deja el resultado registrado.']]],
        'settings' => ['eyebrow' => 'Ajustes', 'title' => 'Configura tu negocio una vez', 'description' => 'Nombre, contacto, identidad visual y datos públicos se controlan desde aquí.', 'steps' => [['title' => 'Completa datos básicos', 'text' => 'Nombre, URL, dirección y WhatsApp.'], ['title' => 'Personaliza la vitrina', 'text' => 'Logo, portada y colores.'], ['title' => 'Guarda y revisa', 'text' => 'Abre Mi tienda para ver el resultado.']]],
    ];
    $guide = $guides[$guideKey] ?? null;
    $storageKey = 'micatalogo_guide_'.$guideKey.'_'.($shop?->public_id ?? $shop?->id ?? 'panel');
@endphp

@if ($guide)
    <section class="mx-auto w-full max-w-[1600px] px-4 pt-4 sm:px-6 lg:px-8" x-data="{ open: true, storageKey: @js($storageKey) }" x-init="open = window.localStorage.getItem(storageKey) !== '1'">
        <div x-show="open" x-cloak class="overflow-hidden rounded-2xl border border-blue-100 bg-gradient-to-r from-blue-50 via-white to-indigo-50 shadow-sm">
            <div class="flex flex-col gap-4 p-4 sm:p-5 lg:flex-row lg:items-center lg:justify-between">
                <div class="max-w-sm">
                    <p class="text-[10px] font-black uppercase tracking-[0.18em] text-blue-700">{{ $guide['eyebrow'] }} · Guía rápida</p>
                    <h2 class="mt-1 text-base font-black text-slate-950">{{ $guide['title'] }}</h2>
                    <p class="mt-1 text-xs leading-5 text-slate-600">{{ $guide['description'] }}</p>
                </div>
                <div class="grid flex-1 gap-2 sm:grid-cols-3">
                    @foreach ($guide['steps'] as $step)
                        <div class="rounded-xl border border-white/90 bg-white/80 p-3">
                            <div class="flex items-center gap-2"><span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blue-600 text-[10px] font-black text-white">{{ $loop->iteration }}</span><p class="text-xs font-black text-slate-800">{{ $step['title'] }}</p></div>
                            <p class="mt-2 text-[11px] leading-4 text-slate-500">{{ $step['text'] }}</p>
                        </div>
                    @endforeach
                </div>
                <button type="button" class="self-start rounded-lg px-2 py-1 text-[11px] font-bold text-slate-500 hover:bg-white hover:text-slate-800 lg:self-center" @click="open = false; window.localStorage.setItem(storageKey, '1')">Ocultar</button>
            </div>
        </div>
        <button x-show="!open" x-cloak type="button" class="mt-1 rounded-full border border-blue-200 bg-white px-3 py-1.5 text-[11px] font-bold text-blue-700 shadow-sm hover:bg-blue-50" @click="open = true; window.localStorage.removeItem(storageKey)">Ver guía: {{ $guide['title'] }}</button>
    </section>
@endif
