<?php

return [
    'seller_menu_options' => [
        'sales' => 'Ventas',
        'products' => 'Productos',
        'printers' => 'Impresoras (app)',
        'quotes' => 'Cotizaciones',
        'orders' => 'Pedidos',
        'encargos' => 'Encargos',
        'shipments' => 'Envíos',
        'day_close' => 'Cierre de día',
        'containers' => 'Contenedores',
        'loads' => 'Cargas',
        'suppliers' => 'Suplidores',
        'purchase_invoices' => 'Facturas',
        'photos' => 'Fotos',
        'storefront' => 'Mi tienda',
        'services' => 'Servicios',
        'price_health' => 'Salud de precios',
        'decants' => 'Decants',
        'attributes' => 'Marcas y atributos',
        'import' => 'Importar',
        'customers' => 'Clientes',
        'credit' => 'Crédito',
        'inventory' => 'Inventario',
        'collections' => 'Cobros',
        'cash' => 'Caja',
        'finance' => 'Finanzas / Ganancias',
        'inventory_adjustments' => 'Ajustes de inventario',
        'partners' => 'Socios',
        'expenses' => 'Gastos',
        'reports' => 'Reportes',
        'commissions' => 'Comisiones',
        'authorizations' => 'Autorizaciones',
        'returns' => 'Devoluciones',
        'routes' => 'Rutas',
        'more' => 'Más herramientas',
        'settings' => 'Ajustes',
        'accountant' => 'Contador',
        'account' => 'Mi cuenta',
        'updates' => 'Novedades',
        'help' => 'Ayuda',
        'practice' => 'Practicar sin miedo',
        'support' => 'Soporte',
        'metrics' => 'Métricas y QR',
        'public_catalog' => 'Compartir catálogo',
        'shop_settings' => 'Configuración de tienda',
        'sellers' => 'Vendedores',
    ],
    'owner_only_menu_options' => [
        'settings',
        'shop_settings',
        'sellers',
    ],
    'android_update' => require __DIR__.'/android-release.php',
];
