<?php

return [
    'implemented' => [
        'products', 'catalog', 'inventory', 'sales', 'customers', 'credit', 'cash',
        'expenses', 'finance', 'decants', 'perfume_fields', 'wholesale', 'brand',
        'sku', 'barcode', 'shipping', 'public_catalog',
    ],

    'types' => [
        'perfume_store' => [
            'label' => 'Perfumes y fragancias',
            'categories' => ['Perfumes', 'Sets', 'Body Splash', 'Decants', 'Accesorios'],
            'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'brand' => true, 'sku' => true, 'barcode' => true, 'perfume_fields' => true, 'decants' => true, 'wholesale' => true, 'public_catalog' => true],
            'product_fields' => ['brand', 'volume_ml', 'concentration', 'gender', 'sku', 'barcode', 'cost_price', 'price', 'stock', 'decants'],
        ],
        'clothing' => [
            'label' => 'Ropa y moda',
            'categories' => ['Camisetas', 'Camisas', 'Pantalones', 'Vestidos', 'Conjuntos', 'Accesorios'],
            'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'brand' => true, 'sku' => true, 'barcode' => true, 'variants' => 'unsupported', 'sizes' => 'unsupported', 'colors' => 'unsupported', 'public_catalog' => true],
            'product_fields' => ['brand', 'size', 'color', 'sku', 'barcode', 'cost_price', 'price', 'stock'],
        ],
        'footwear' => [
            'label' => 'Calzado y tenis',
            'categories' => ['Tenis', 'Zapatos', 'Sandalias', 'Botas', 'Accesorios'],
            'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'brand' => true, 'sku' => true, 'barcode' => true, 'variants' => 'unsupported', 'sizes' => 'unsupported', 'colors' => 'unsupported', 'public_catalog' => true],
            'product_fields' => ['brand', 'model', 'size', 'color', 'sku', 'barcode', 'cost_price', 'price', 'stock'],
        ],
        'beauty_cosmetics' => ['label' => 'Belleza y cosméticos', 'categories' => ['Maquillaje', 'Cuidado facial', 'Cuidado capilar', 'Cuidado corporal', 'Accesorios'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'brand' => true, 'sku' => true, 'barcode' => true, 'public_catalog' => true], 'product_fields' => ['brand', 'sku', 'barcode', 'cost_price', 'price', 'stock']],
        'barbershop' => ['label' => 'Barbería', 'categories' => ['Cortes', 'Barba', 'Tratamientos', 'Cuidado capilar', 'Cuidado de barba', 'Accesorios'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'public_catalog' => true, 'services' => 'unsupported', 'appointments' => 'unsupported'], 'product_fields' => ['brand', 'size', 'cost_price', 'price', 'stock']],
        'beauty_salon' => ['label' => 'Salón de belleza y uñas', 'categories' => ['Cabello', 'Uñas', 'Maquillaje', 'Tratamientos', 'Productos'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'public_catalog' => true, 'services' => 'unsupported', 'appointments' => 'unsupported'], 'product_fields' => ['brand', 'size', 'cost_price', 'price', 'stock']],
        'electronics' => ['label' => 'Tecnología y electrónica', 'categories' => ['Celulares', 'Computadoras', 'Accesorios', 'Audio', 'Redes', 'Otros'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'brand' => true, 'model' => true, 'sku' => true, 'barcode' => true, 'wholesale' => true, 'public_catalog' => true, 'serial_tracking' => 'unsupported'], 'product_fields' => ['brand', 'model', 'sku', 'barcode', 'cost_price', 'price', 'stock']],
        'accessories_jewelry' => ['label' => 'Accesorios y joyería', 'categories' => ['Relojes', 'Cadenas', 'Pulseras', 'Aretes', 'Bolsos', 'Otros'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'brand' => true, 'sku' => true, 'barcode' => true, 'public_catalog' => true], 'product_fields' => ['brand', 'model', 'color', 'sku', 'barcode', 'cost_price', 'price', 'stock']],
        'food_restaurant' => ['label' => 'Restaurante y alimentos', 'categories' => ['Entradas', 'Platos', 'Bebidas', 'Postres', 'Combos'], 'capabilities' => ['products' => true, 'catalog' => true, 'sales' => true, 'customers' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'public_catalog' => true, 'inventory' => 'unsupported', 'recipes_or_ingredients' => 'unsupported', 'weighted_products' => 'unsupported'], 'product_fields' => ['description', 'price', 'stock']],
        'grocery' => ['label' => 'Colmado y minimarket', 'categories' => ['Alimentos', 'Bebidas', 'Higiene', 'Limpieza', 'Hogar', 'Otros'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'sku' => true, 'barcode' => true, 'public_catalog' => true, 'weighted_products' => 'unsupported'], 'product_fields' => ['sku', 'barcode', 'cost_price', 'price', 'stock']],
        'hardware' => ['label' => 'Ferretería', 'categories' => ['Herramientas', 'Electricidad', 'Plomería', 'Pintura', 'Construcción', 'Tornillería'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'brand' => true, 'sku' => true, 'barcode' => true, 'wholesale' => true, 'public_catalog' => true], 'product_fields' => ['brand', 'sku', 'barcode', 'cost_price', 'price', 'stock']],
        'auto_parts' => ['label' => 'Repuestos y automotriz', 'categories' => ['Motor', 'Frenos', 'Suspensión', 'Electricidad', 'Filtros', 'Accesorios'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'brand' => true, 'model' => true, 'sku' => true, 'barcode' => true, 'wholesale' => true, 'public_catalog' => true], 'product_fields' => ['brand', 'model', 'sku', 'barcode', 'cost_price', 'price', 'stock']],
        'home_furniture' => ['label' => 'Hogar y muebles', 'categories' => ['Sala', 'Comedor', 'Dormitorio', 'Cocina', 'Decoración', 'Otros'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'sku' => true, 'barcode' => true, 'public_catalog' => true], 'product_fields' => ['color', 'sku', 'barcode', 'cost_price', 'price', 'stock']],
        'pharmacy_personal_care' => ['label' => 'Farmacia y cuidado personal', 'categories' => ['Cuidado personal', 'Higiene', 'Belleza', 'Accesorios', 'Otros'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'brand' => true, 'sku' => true, 'barcode' => true, 'public_catalog' => true], 'product_fields' => ['brand', 'sku', 'barcode', 'cost_price', 'price', 'stock']],
        'professional_services' => ['label' => 'Servicios profesionales', 'categories' => ['Servicios', 'Paquetes', 'Otros'], 'capabilities' => ['sales' => true, 'customers' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'catalog' => true, 'public_catalog' => true, 'services' => 'unsupported', 'products' => 'unsupported', 'inventory' => false], 'product_fields' => ['description', 'price']],
        'general_retail' => ['label' => 'Tienda general', 'categories' => ['Productos', 'Ofertas', 'Otros'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'sku' => true, 'barcode' => true, 'public_catalog' => true], 'product_fields' => ['sku', 'barcode', 'cost_price', 'price', 'stock']],
        'other' => ['label' => 'Otro tipo de negocio', 'categories' => ['Productos', 'Servicios', 'Otros'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'public_catalog' => true], 'product_fields' => ['description', 'sku', 'barcode', 'cost_price', 'price', 'stock']],
        // Additional stable keys observed in Puntto's public registration.
        'vapes' => ['label' => 'Vapes', 'categories' => ['Dispositivos', 'Líquidos', 'Accesorios', 'Otros'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'sku' => true, 'barcode' => true, 'public_catalog' => true], 'product_fields' => ['brand', 'model', 'sku', 'barcode', 'cost_price', 'price', 'stock']],
        'pastry' => ['label' => 'Repostería', 'categories' => ['Pasteles', 'Postres', 'Panadería', 'Combos'], 'capabilities' => ['products' => true, 'catalog' => true, 'sales' => true, 'customers' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'public_catalog' => true, 'inventory' => 'unsupported'], 'product_fields' => ['description', 'price']],
        'tattoo_studio' => ['label' => 'Tatuajes', 'categories' => ['Tatuajes', 'Diseños', 'Accesorios'], 'capabilities' => ['sales' => true, 'customers' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'catalog' => true, 'public_catalog' => true, 'services' => 'unsupported', 'products' => 'unsupported'], 'product_fields' => ['description', 'price']],
        'caps_store' => ['label' => 'Gorras', 'categories' => ['Gorras', 'Accesorios', 'Otros'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'brand' => true, 'sku' => true, 'barcode' => true, 'public_catalog' => true], 'product_fields' => ['brand', 'size', 'color', 'sku', 'barcode', 'cost_price', 'price', 'stock']],
        'boutique' => ['label' => 'Boutique', 'categories' => ['Ropa', 'Vestidos', 'Accesorios', 'Otros'], 'capabilities' => ['products' => true, 'catalog' => true, 'inventory' => true, 'sales' => true, 'customers' => true, 'credit' => true, 'cash' => true, 'expenses' => true, 'finance' => true, 'brand' => true, 'sku' => true, 'barcode' => true, 'public_catalog' => true], 'product_fields' => ['brand', 'size', 'color', 'sku', 'barcode', 'cost_price', 'price', 'stock']],
    ],

    'reserved_slugs' => ['admin', 'api', 'login', 'register', 'panel', 'tienda', 'tiendas', 'logout', 'forgot-password'],
];
